#!/bin/bash
docker run --rm -d --net host --hostname nomad-server.integrationtest ynux/cluster-broccoli-test nomad > nomad.did
sleep $BROCCOLI_SLEEP_MEDIUM
docker run --rm -d --net host ynux/cluster-broccoli-test cluster-broccoli -Dconfig.file="/application-tls.conf" > cluster-broccoli.did
sleep $BROCCOLI_SLEEP_MEDIUM
