#!/bin/bash
docker run --rm -d --net host --hostname nomad-server.integrationtest sunygit/cluster-broccoli-test nomad > nomad.did
sleep $BROCCOLI_SLEEP_MEDIUM
docker run --rm -d --net host sunygit/cluster-broccoli-test cluster-broccoli -Dconfig.file="/application-tls.conf" -Dbroccoli.nomad.url=https://localhost:4646 > cluster-broccoli.did
sleep $BROCCOLI_SLEEP_MEDIUM
