#!/bin/bash
docker run --rm -d --net host ynux/cluster-broccoli-test consul > consul.did
sleep $BROCCOLI_SLEEP_MEDIUM
docker run --rm -d --net host -v /var/run/docker.sock:/var/run/docker.sock ynux/cluster-broccoli-test nomad > nomad.did
sleep $BROCCOLI_SLEEP_MEDIUM
docker run --rm -d --net host ynux/cluster-broccoli-test cluster-broccoli -Dconfig.file="/application-tls.conf" > cluster-broccoli.did
sleep $BROCCOLI_SLEEP_MEDIUM
curl -s http://localhost:9000 > /dev/null && echo "Broccoli started successfully" || echo "Broccoli did not start, yet"
