#!/bin/bash
docker pull couchdb:1.7.0
docker run --rm -d --net host couchdb:1.7.0 > couchdb.did

sleep $BROCCOLI_SLEEP_MEDIUM

docker run --rm -d --net host \
  sunygit/cluster-broccoli-test \
  cluster-broccoli \
  -Dconfig.file="/couchdb-tls.conf" > cluster-broccoli.did

sleep $BROCCOLI_SLEEP_MEDIUM

curl -s http://localhost:9000 > /dev/null && echo "Broccoli started successfully" || echo "Broccoli did not start, yet"
